fix(payment-processor): Update image tag to v4

diff --git a/manifests/workloads/payment-processor.yaml b/manifests/workloads/payment-processor.yaml
--- a/manifests/workloads/payment-processor.yaml
+++ b/manifests/workloads/payment-processor.yaml
@@ -1,18 +1,10 @@
-apiVersion: v1
-kind: Namespace
-metadata:
-  name: prod-payments
-  labels:
-    cost-center: "finops-payments-101"
-    owner: "payments-team"
-    pod-security.kubernetes.io/enforce: "baseline"
----
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: payment-processor
   namespace: prod-payments
   labels:
+    app: payment-processor
 spec:
   replicas: 2
   selector:
@@ -24,13 +16,13 @@ spec:
         app: payment-processor
     spec:
       containers:
-        - name: app
-          image: bash:latest
-          command: ["/bin/sh", "-c"]
-          args:
-            - |
-              if [ -z "$DATABASE_URL" ]; then
-                echo "FATAL: Mandatory environment variable DATABASE_URL is missing!"
-                exit 1
-              fi
-              echo "Starting payment service..."
+      - name: app
+        image: gcr.io/google-samples/gb-frontend:v4
+        command: ["/bin/sh", "-c"]
+        args:
+        - |
+          if [ -z "$DATABASE_URL" ]; then
+            echo "FATAL: Mandatory environment variable DATABASE_URL is missing!"
+            exit 1
+          fi
+          echo "Starting payment service..."
